-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."user"
(
    email character varying NOT NULL,
    "name" character varying NOT NULL,
    password character varying NOT NULL,
    role character varying NOT NULL,
    "balance" numeric(12,2) NOT NULL,
    PRIMARY KEY (email)
);

CREATE TABLE IF NOT EXISTS public.toppings
(
    id serial NOT NULL,
    name character varying NOT NULL,
    price integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.bottoms
(
    id serial NOT NULL,
    name character varying NOT NULL,
    price integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.cupcake
(
    id serial NOT NULL,
    toppings_id integer NOT NULL,
    bottoms_id integer NOT NULL,
    cupcake_price integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."order"
(
    id serial NOT NULL,
    email character varying NOT NULL,
    date date NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.order_holder
(
    order_holder_id serial NOT NULL,
    order_id integer NOT NULL,
    cupcake_id integer NOT NULL,
    quantity integer NOT NULL DEFAULT 1,
    PRIMARY KEY (order_holder_id)
);

ALTER TABLE IF EXISTS public.cupcake
    ADD FOREIGN KEY (toppings_id)
    REFERENCES public.toppings (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.cupcake
    ADD FOREIGN KEY (bottoms_id)
    REFERENCES public.bottoms (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."order"
    ADD FOREIGN KEY (email)
    REFERENCES public."user" (email) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.order_holder
    ADD FOREIGN KEY (order_id)
    REFERENCES public."order" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;